services:
  app:
    build:
      context: "./"
    networks:
      - emftillweb
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"

  postgres:
    build:
      context: "./docker/data/"
    networks:
      - emftillweb

networks:
  emftillweb:
