# Generated by Django 3.2.12 on 2022-04-29 16:42

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening_time', models.DateTimeField(help_text='Time we open')),
                ('closing_time', models.DateTimeField(help_text='Time we close')),
                ('weight', models.FloatField(help_text='Expected busyness of session')),
                ('comment', models.CharField(blank=True, help_text='Displayed on web interface; not private!', max_length=100)),
            ],
            options={
                'ordering': ('opening_time',),
            },
        ),
        migrations.AddConstraint(
            model_name='session',
            constraint=models.CheckConstraint(check=models.Q(('closing_time__gt', django.db.models.expressions.F('opening_time'))), name='ends_after_start'),
        ),
    ]
