# Generated by Django 3.2.13 on 2022-05-21 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emf', '0003_displaypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='path',
            field=models.CharField(blank=True, help_text="Used to form the URL for the page. Lower-case, no spaces, do not include leading or trailing '/'. Blank for front page.", max_length=80, unique=True),
        ),
    ]
