# Generated by Django 3.2.13 on 2022-06-21 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emf', '0004_alter_page_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='displaypage',
            name='template',
            field=models.CharField(blank=True, choices=[('Display', 'Blank display'), ('OnTap', 'Drinks on tap'), ('CansAndBottles', 'Craft cans and bottles'), ('Wines', 'Wines and wine cans'), ('WinesAndSpirits', 'Wines and spirits'), ('SpiritsAndMixers', 'Spirits and mixers'), ('ClubMate', 'Club Mate'), ('SoftDrinks', 'Soft drinks'), ('Progress', 'Event progress'), ('ProgressFacts', 'Bar Fun Facts'), ('OpeningTimes', 'Bar opening times')], help_text='Programmed template for the page', max_length=80),
        ),
    ]
